inherit_from:
  - .rubocop_rspec_base.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true

# Over time we'd like to get this down, but this is what we're at now.
LineLength:
  Max: 186

# Offense count: 1
Style/BlockComments:
  Enabled: false

# We have some situations where we need to use `raise ExceptionClass.new(argument)`.
Style/RaiseArgs:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  Exclude:
    - REPORT_TEMPLATE.md

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: []
    '%r':   '||'

Security/Eval:
  Exclude:
    - Gemfile

Metrics/AbcSize:
  Max: 26

# Offense count: 2
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 96
  Exclude:
    - spec/**/*

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 236
  Exclude:
    - spec/**/*

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 14

AccessModifierIndentation:
  Exclude:
    - 'lib/rspec/expectations/syntax.rb' # Too much diff to fix

# Offense count: 7
Layout/AlignParameters:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/*'

# Offense count: 6
Lint/IneffectiveAccessModifier:
  Exclude:
    - 'lib/rspec/matchers.rb'
    - 'lib/rspec/matchers/built_in/compound.rb'
    - 'lib/rspec/matchers/expecteds_for_multiple_diffs.rb'
    - 'lib/rspec/matchers/generated_descriptions.rb'

Lint/InheritException:
  Exclude:
    - 'lib/rspec/expectations.rb'

Bundler/DuplicatedGem:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
