inherit_from:
  - .rubocop_rspec_base.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Exclude:
    - bin/*
    - tmp/**/*

# Over time we'd like to get this down, but this is what we're at now.
LineLength:
  Max: 186

# Offense count: 1
Style/BlockComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*

Style/EvalWithLocation:
  Exclude:
    - spec/rspec/matchers/built_in/respond_to_spec.rb

Style/MultilineBlockChain:
  Exclude:
    - spec/**/*

Style/RescueModifier:
  Exclude:
    - spec/**/*
    - benchmarks/**/*

Style/Semicolon:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - spec/**/*
    - benchmarks/**/*

# We have some situations where we need to use `raise ExceptionClass.new(argument)`.
Style/RaiseArgs:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  Exclude:
    - REPORT_TEMPLATE.md

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: []
    '%r':   '||'

Style/WordArray:
  Enabled: false

Security/Eval:
  Exclude:
    - Gemfile

Metrics/AbcSize:
  Max: 26

# Offense count: 2
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 96
  Exclude:
    - spec/**/*

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 239
  Exclude:
    - spec/**/*

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 14

AccessModifierIndentation:
  Exclude:
    - 'lib/rspec/expectations/syntax.rb' # Too much diff to fix

# Offense count: 7
Layout/AlignParameters:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - spec/rspec/matchers/built_in/contain_exactly_spec.rb

Layout/SpaceInsideParens:
  Exclude:
    - spec/rspec/matchers/built_in/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/*'

Lint/HandleExceptions:
  Exclude:
    - benchmarks/**/*

# Offense count: 3
Lint/IneffectiveAccessModifier:
  Exclude:
    - 'lib/rspec/matchers.rb'
    - 'lib/rspec/matchers/built_in/compound.rb'

Lint/InheritException:
  Exclude:
    - 'lib/rspec/expectations.rb'

Bundler/DuplicatedGem:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
