# In order to install old Rubies, we need to use old Ubuntu distibution.
dist: trusty
language: ruby
email: false
cache:
  directories:
    - ../bundle
before_install:
  - "script/update_rubygems_and_install_bundler"
  - unset _JAVA_OPTIONS
  - "script/clone_all_rspec_repos"
bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
script: "script/run_build"
rvm:
  - jruby-9.1.7.0 # pin JRuby to this until travis/rvm can install later versions
  - jruby-head
env:
  - JRUBY_OPTS='--dev'
  - RSPEC_CI='true'
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
branches:
  only:
    - main
    - /^\d+-\d+-maintenance$/
    - /^\d+-\d+-dev$/
